name: test-conda-env
channels:
- conda-forge
- nodefaults
dependencies:
- python=3
- pandoc
- numpy
- cmake
- sphinx
- pip:
  - "nanobind"
  - "pytest"
  - "scikit-build-core[pyproject]"
  - "sphinx-math-dollar"
  - "pytools"
  - "sphinx-copybutton"
  - "insipid_sphinx_theme"
  - "IPython"
  - "ipykernel"
  - "jupyter"
  - "nbsphinx"
