# Conda env file for the readthedocs build
name: rtd-env-py3
channels:
- conda-forge
- nodefaults
dependencies:
- python=3.12
- pandoc
- numpy
- cmake
- pip:
  - "nanobind"
  - "scikit-build-core[pyproject]"
  - "sphinx-math-dollar"
  - "pytools"
  - "sphinx-copybutton"
  - "insipid_sphinx_theme"
  - "IPython"
  - "ipykernel"
  - "jupyter"
