name: CI
on:
  push:
    branches:
      - main
    pull_request:
      schedule:
        - cron:  '17 3 * * 0'

jobs:
  build-docs:
    name: Check Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: "3"
          auto-activate-base: false
          auto-update-conda: true

      - name: Create test-conda-env, install pybliss, sphinx-build
        run: |
          conda init bash
          source ~/.bashrc
          conda env create -f .test-conda-env.yml
          conda activate test-conda-env
          pip install .
          cd docs
          make html SPHINXOPTS="-W --keep-going -n"
